<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use Carbon\Carbon;

class PostJobsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('post_jobs')->insert([
            [
                'id' => 1,
                'title' => 'Backend Engineer',
                'company' => 'Bytewave Solutions',
                'location' => 'Austin, TX',
                'type' => 'Full-time',
                'salary' => '$110,000 - $135,000',
                'description' => 'Build and maintain scalable APIs and microservices. Collaborate with frontend and DevOps teams in an agile environment.',
                'requirements' => "4+ years in backend development\nStrong experience with Node.js and PostgreSQL\nFamiliar with Docker and CI/CD pipelines\nExcellent problem-solving skills",
                'posted_date' => '2025-03-20',
                'deadline' => '2025-04-18',
                'category' => 'Software Development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 2,
                'title' => 'DevOps Engineer',
                'company' => 'Bytewave Solutions',
                'location' => 'Remote',
                'type' => 'Full-time',
                'salary' => '$175,000 - $125,000',
                'description' => 'Implement and manage CI/CD pipelines, automate infrastructure, and ensure high availability of services.',
                'requirements' => "3+ years of experience in DevOps\nProficiency with AWS, Docker, and Kubernetes\nExperience with monitoring and logging tools\nStrong scripting skills (Bash, Python)",
                'posted_date' => '2025-03-22',
                'deadline' => '2025-04-25',
                'category' => 'DevOps',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 3,
                'title' => 'Frontend Developer',
                'company' => 'Bytewave Solutions',
                'location' => 'Seattle, WA',
                'type' => 'Hybrid',
                'salary' => '$95,000 - $115,000',
                'description' => 'Develop and enhance user-facing features with a strong focus on performance and usability.',
                'requirements' => "3+ years in frontend development\nProficient in Angular or React\nExperience with responsive and mobile-first design\nSolid knowledge of HTML, CSS, JavaScript/TypeScript",
                'posted_date' => '2025-03-18',
                'deadline' => '2025-04-20',
                'category' => 'Software Development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 4,
                'title' => 'Digital Marketing Manager',
                'company' => 'NovaReach Media',
                'location' => 'Remote',
                'type' => 'Full-time',
                'salary' => '$85,000 - $95,000',
                'description' => 'Drive online marketing campaigns, oversee content strategy, and analyze performance metrics.',
                'requirements' => "3+ years in digital marketing\nExpertise in Google Ads, SEO, and analytics\nStrong content writing and planning skills\nExperience with marketing automation tools",
                'posted_date' => '2025-03-21',
                'deadline' => '2025-04-22',
                'category' => 'Marketing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 5,
                'title' => 'Content Strategist',
                'company' => 'NovaReach Media',
                'location' => 'Chicago, IL',
                'type' => 'Full-time',
                'salary' => '$70,000 - $80,000',
                'description' => 'Craft compelling content strategies to drive user engagement across web and social channels.',
                'requirements' => "Bachelor's in Marketing, Communications, or related field\n2+ years in content strategy or copywriting\nSEO knowledge and keyword research skills\nExcellent storytelling ability",
                'posted_date' => '2025-03-24',
                'deadline' => '2025-04-26',
                'category' => 'Marketing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 6,
                'title' => 'PPC Specialist',
                'company' => 'NovaReach Media',
                'location' => 'New York, NY',
                'type' => 'Full-time',
                'salary' => '$75,000 - $90,000',
                'description' => 'Manage pay-per-click campaigns, perform A/B testing, and optimize for conversion.',
                'requirements' => "2+ years managing Google Ads and Bing campaigns\nStrong knowledge of SEM tools\nAnalytical mindset with ROI-focused approach\nFamiliar with landing page optimization",
                'posted_date' => '2025-03-26',
                'deadline' => '2025-04-23',
                'category' => 'Marketing',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 7,
                'title' => 'UI/UX Designer',
                'company' => 'Creatix Studios',
                'location' => 'San Francisco, CA',
                'type' => 'Contract',
                'salary' => '$60,000 - 65,000',
                'description' => 'Design wireframes, mockups, and prototypes with a focus on intuitive and elegant user experiences.',
                'requirements' => "2+ years in UI/UX design\nProficiency in Figma or Adobe XD\nStrong portfolio of user-focused designs\nFamiliarity with accessibility standards",
                'posted_date' => '2025-03-19',
                'deadline' => '2025-04-27',
                'category' => 'Design',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 8,
                'title' => 'Product Designer',
                'company' => 'Creatix Studios',
                'location' => 'Remote',
                'type' => 'Full-time',
                'salary' => '$90,000 - $110,000',
                'description' => 'Collaborate with product and engineering teams to deliver innovative and elegant design solutions.',
                'requirements' => "3+ years in product design\nExperience working on SaaS platforms\nAbility to conduct usability testing\nStrong visual and interaction design skills",
                'posted_date' => '2025-03-29',
                'deadline' => '2025-04-24',
                'category' => 'Design',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 9,
                'title' => 'Motion Graphic Designer',
                'company' => 'Creatix Studios',
                'location' => 'Los Angeles, CA',
                'type' => 'Part-time',
                'salary' => '$45,000 - $60,000',
                'description' => 'Create animations and videos for digital campaigns, social media, and product demos.',
                'requirements' => "2+ years in motion design\nProficiency in After Effects, Premiere Pro\nCreative eye for animation and timing\nExperience in storytelling through video",
                'posted_date' => '2025-03-23',
                'deadline' => '2025-04-28',
                'category' => 'Design',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id' => 10,
                'title' => 'Brand Designer',
                'company' => 'Creatix Studios',
                'location' => 'New York, NY',
                'type' => 'Full-time',
                'salary' => '$80,000 - $95,000',
                'description' => 'Develop and maintain brand visuals, including logos, typography, and brand guidelines.',
                'requirements' => "Bachelor’s in Design or related field\nStrong graphic design portfolio\nExperience with brand identity systems\nAttention to detail and creativity",
                'posted_date' => '2025-03-28',
                'deadline' => '2025-04-29',
                'category' => 'Design',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
