<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $report->title }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 20px; }
        .header { background-color: #2196F3; color: white; padding: 20px; text-align: center; }
        .content { margin: 20px 0; }
        .info-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        .info-table th, .info-table td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        .info-table th { background-color: #f2f2f2; }
        .footer { margin-top: 40px; text-align: center; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <h1>{{ $report->title }}</h1>
        <p>Generated on: {{ $generated_at }}</p>
    </div>
    
    <div class="content">
        <h2>Report Information</h2>
        <table class="info-table">
            <tr><th>Type</th><td>{{ $report->type }}</td></tr>
            <tr><th>Description</th><td>{{ $report->description ?? 'N/A' }}</td></tr>
            <tr><th>Last Updated</th><td>{{ $report->last_updated->format('Y-m-d H:i:s') }}</td></tr>
            <tr><th>Views</th><td>{{ $report->views }}</td></tr>
            <tr><th>Downloads</th><td>{{ $report->downloads }}</td></tr>
        </table>
        
        <h2>Sample Data</h2>
        <table class="info-table">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Metric</th>
                    <th>Value</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($sample_data as $data)
                <tr>
                    <td>{{ $data['date'] }}</td>
                    <td>{{ $data['metric'] }}</td>
                    <td>{{ $data['value'] }}</td>
                    <td>{{ $data['status'] }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    
    <div class="footer">
        <p>Generated by Job Seeker System</p>
    </div>
</body>
</html>