services:
  - type: web
    name: laravel-app
    runtime: docker
    plan: free
    branch: master
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:Yam5vNTkQy/c7L7OKU2zJ4RLIO8qX+ijjMck82UQUMk=
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your_db
      - key: DB_USERNAME
        value: your_user
      - key: DB_PASSWORD
        value: your_password
